version: '3'

networks:
    app-network:

services:
  app:
    image: opencartbrasil/opencartbrasil:latest
    container_name: app
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - 80:80
    environment:
      OCBR_HTTP_SERVER: "http://localhost/"
      OCBR_DB_HOST: "db"
      OCBR_DB_USER: "store"
      OCBR_DB_PASS: "store"
      OCBR_DB_DATABASE: "opencartbrasil"
      OCBR_ADMIN_USER: "admin"
      OCBR_ADMIN_PASS: "123456"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: store
      MYSQL_PASSWORD: store
      MYSQL_DATABASE: opencartbrasil
    networks:
      - app-network